[project]
name = "hass-miner"
version = "1.2.7-rc2"
description = "A home assistant integration for asic miners, using asic-rs"
authors = [
    {name = "Michael Schmid", email = "michael@amazee.com"}
]
readme = "README.md"
requires-python = ">=3.14.2,<4.0"
package-mode = false
dependencies = [
    "pyasic-rs>=0.6.2",
    "homeassistant>=2026.1.0",
    "ruff>=0.15.16",
]
