name: Manage labels

on:
  push:
    branches:
      - main
      - master

jobs:
  labeler:
    name: Labeler
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.1.0

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          skip-delete: true
